# Generated by Django 4.0.5 on 2022-06-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shorturl',
            name='name',
        ),
        migrations.AddField(
            model_name='shorturl',
            name='slug',
            field=models.SlugField(default='Untitled', max_length=30, unique=True),
        ),
    ]
