# Generated by Django 4.0.5 on 2022-06-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_remove_shorturl_name_shorturl_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='slug',
            field=models.SlugField(default='Untitled', max_length=30),
        ),
    ]
