# Generated by Django 4.0.5 on 2022-06-30 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_alter_shorturl_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='slug',
            field=models.SlugField(max_length=30, null=True),
        ),
    ]
